### ISSUE TITLE
[Feature Request] Display rotation possible?

### ISSUE THREAD

**Issue by lechk82** [strange-v/ha_deck#11]
First of all: I have been searching for a way to integrate LVGL and esphome for a long time, and I am very impressed by this project.
Is there a way to adjust the display orientation using the rotation parameter?

**Comment by strange-v** [comment]
Two options:
1. Clone the repo and do this #7 
2. Optionally, make it configurable via YAML and create a PR.

**Comment by multinet33** [comment]
Hello I tried with value 0 ; 2 ; 3 but the screen is rotatted only bu 90° right and with a lot of glitch. Any help on the correct value to use ?

**Comment by lechk82** [comment]
> Hello I tried with value 0 ; 2 ; 3 but the screen is rotatted only bu 90° right and with a lot of glitch. Any help on the correct value to use ?

I initially had the same problem and solved it as follows:

hd_device_sc01_plus.cpp:
```
    disp_drv.rotated = 0;
    disp_drv.sw_rotate = 0;
```

LGFX.cpp:
```
cfg.offset_rotation = 2;
```
![Uploading 20240216_214159.jpg…]()

**Comment by multinet33** [comment]
Oh OK, my need is a bit different, I need to rotate by 180° (because of my dock I cant put the screen in the other way)

Do you know the value for 180° ?

Thank you !

**Comment by lechk82** [comment]
Tested 0,1,2,3 for `cfg.offset_rotation = 2;` giving me 0, 90,180,270 degrees, respectively. choose the one you like

**Comment by brixharlem** [comment]
> Tested 0,1,2,3 for `cfg.offset_rotation` giving me 0, 90,180,270 degrees, respectively. choose the one you like

Hi @lechk82,
it worked well to rotate the screen. The touch did not rotate in my case. Can you pls let me know, how you rotated the touch?
Thank you!!

**Comment by multinet33** [comment]
Hello do you modify the 2 occurences of cfg.offset_rotation in LGFX.cpp or only one ?
do you modify anything in hd_device_sc01_plus ? (what is your values of     disp_drv.rotated and    disp_drv.sw_rotate ) ?
thank you

**Comment by brixharlem** [comment]
@multinet33 My mistake was, that I changed cfg.offset_rotation = 0; in line 73. Changing cfg.offset_rotation in line 40 works for me.

**Comment by genasoft** [comment]
For the life in me, I can't figure this one out. I did set disp_drv.rotated = 0; and disp_drv.sw_rotate = 0; and I also changed both line 40 and 73 to 2. Screen is still in Landscape. Am I missing something?

**Comment by lechk82** [comment]
Make sure that disp_drv.rotated = 0; and disp_drv.sw_rotate = 0 are not overwritten, as esphome will sometimes pulls the git sources

**Comment by genasoft** [comment]
I cloned the git - https://github.com/genasoft/ha_deck/blob/main/components/hd_device_sc01_plus/hd_device_sc01_plus.cpp and they are set to 0. On top, this clone is brand new as I wanted to start fresh (initially I thought that this might be causing the problem).
I have also deleted the instance in ESPhome (HA) - all cleaned from BUILD, STORAGE and IDEDATA.
Do I need to swap HEIGHT and WIDTH variables?

**Comment by lechk82** [comment]
apart from the changes mentioned, i haven't changed anything else, so specifically only this:
> 
> hd_device_sc01_plus.cpp:
> 
> ```
>     disp_drv.rotated = 0;
>     disp_drv.sw_rotate = 0;
> ```
> 
> LGFX.cpp:
> 
> ```
> cfg.offset_rotation = 2;
> ```
>

**Comment by lechk82** [comment]
You could fork the repo, hardcode the rotation settings in your fork end use that one directly as a component.

**Comment by genasoft** [comment]
I am deleting the full build directory, so unless there is somewhere else cache, that shouldn't be the case.
strange-v, any idea that would help solve the issue?

**Comment by genasoft** [comment]
> You could fork the repo, hardcode the rotation settings in your fork end use that one directly as a component.

This is what I did - https://github.com/genasoft/ha_deck/tree/main

**Comment by lechk82** [comment]
right, i've just seen it, i'll try your component and see what comes out for me

**Comment by lechk82** [comment]
your fork gave me an error, so I forked it myself and it works as expected. I also removed the background image because it overshoots the rotated image area. try it with my fork: https://github.com/lechk82/ha_deck

**Comment by genasoft** [comment]
Ha, it worked with your fork. This is very weird.
Thanks

**Comment by multinet33** [comment]
I compile it via ESPhome under home assistant

before I always make a clean build files so it download all dependencies every times

is it the correct way to do it ?

i think yes because every time I put back 0 I get my screen landscape (but I would like it in 180 degrees because I can’t reverse my screen due to my case)

**Comment by koalatje2000** [comment]
I have also the issue that I can not rotate it by 180 degrees also tried what other people did above. And i also did a clean install everytime so it will not use the cached GitHub repo in esphome.

**Comment by lukedoomer** [comment]
@koalatje2000 @multinet33 

configuration of 180' rotation

LGFX.cpp
###
    cfg.offset_rotation = 2;
###

hd_device_sc01_plus.cpp
###
    disp_drv.rotated = 1;
    disp_drv.sw_rotate = 1;
###

**Comment by multinet33** [comment]
Hello @lukedoomer 

I've putted the setting in my fork ( https://github.com/multinet33/ha_deck )

but after compiling (all) my screen is in portrait mode (not landscape 180°) 

When 0 is set to 0 my screen is in landscape but I need to rotate it at 180
