### ISSUE TITLE
Icons issue

### ISSUE THREAD

**Issue by ssttaarr33** [strange-v/ha_deck#12]
How do you know which icon to put where? They aren't rendered in esphome or github, just a small square with a question mark in it. 
I understand that they are here: https://pictogrammers.com/docs/library/mdi/guides/home-assistant/ but how do you use them?

**Comment by strange-v** [comment]
There is no super easy way. Usually, I search for an icon here https://pictogrammers.com/library/mdi/, and the visually check if it present in the HA list. Alternatively, you can use "edit on github" option, and it'll show all icon codes:
`| Logos            | <Icon name='mdi:home-assistant' /> <Icon name='mdi:google-assistant' /> <Icon name='mdi:apple' /> <Icon name='mdi:zigbee' /> <Icon name='mdi:z-wave' /> |`

**Comment by ssttaarr33** [comment]
> There is no super easy way. Usually, I search for an icon here https://pictogrammers.com/library/mdi/, and then visually check if it present in the HA list. Alternatively, you can use "edit on github" option, and it'll show all icon codes: `| Logos | <Icon name='mdi:home-assistant' /> <Icon name='mdi:google-assistant' /> <Icon name='mdi:apple' /> <Icon name='mdi:zigbee' /> <Icon name='mdi:z-wave' /> |`

thanks for the prompt reply. On which file do you suggest to use "edit on github"?

**Comment by ssttaarr33** [comment]
ah, yeah, i get that. But..if i define a button like this:
        - type: button
          position: 244, 8
          text: VaCUUM
          icon: mdi:robot-vacuum
          enabled: return true;
          on_click:
        .....

The icon will not be rendered

**Comment by strange-v** [comment]
In the next version (in case I manage to finish its development), icons will be defined like this:
```yaml
- type: button
  position: 126, 376
  text: Lights
  icon: F18DD
  enabled: return false;
```

Currently, only glyph is supported.

**Comment by ssttaarr33** [comment]
and is there any way to find the mapping between glyps and mdi: icons?

**Comment by strange-v** [comment]
It'll be hard to map in this direction. The glyph can be converted to code, then open the ttf font in VC Code and search by the code.
But usually, you need a glyph for the website icon, which can be copied by clicking on the icon.
![image](https://github.com/strange-v/ha_deck/assets/3875529/b8e12a79-e112-4d46-89e5-fd85382a2f45)

**Comment by ssttaarr33** [comment]
Ok. I managed to find a way to use the icons I wanted to. Now, i have an issue with calling homeassistant services. What is wrong with this?
![image](https://github.com/strange-v/ha_deck/assets/9638926/b8c06049-1a8f-4ef0-bbcc-1d6de516c6b5)

**Comment by ssttaarr33** [comment]
> Have you allowed this device to make Home Assistant service calls?

now i did and it works fine. You can close the issue. Thanks a lot for the support
