### ISSUE TITLE
Initial flash

### ISSUE THREAD

**Issue by skybarberom** [strange-v/ha_deck#13]
I've been trying to make the initial installation on esphome but if I flash it from web or I manually flash it, the screen can't connect to wifi and it's off. I hadn't this problem with openhasp but it was too much effort to program. Any advice how to flash it correctly?

**Comment by strange-v** [comment]
What device are you using?

**Comment by strange-v** [comment]
I'd suggest starting with bare ESPHome, and if it works adding ha_deck components. Currently, it is unclear whether it is hardware, ESPHome, or Ha Deck faults.
