### ISSUE TITLE
Camera integration

### ISSUE THREAD

**Issue by set-st** [strange-v/ha_deck#14]
Is it possible to create page with cameras buttons, and with click on it open page with video stream from HA?

**Comment by strange-v** [comment]
Short answer - no.

**Comment by strange-v** [comment]
Long answer: I've seen a mjpeg decoder for esp32, so, theoretically, it is possible, but it isn't a trivial task. It requires a lot of investment (time) and does not guarantee any results. I have no plans to dig in that direction.
