### ISSUE TITLE
possible expand on ESP32-2432S028R

### ISSUE THREAD

**Issue by 1achy** [strange-v/ha_deck#3]

**Comment by 1achy** [comment]
[https://m.media-amazon.com/images/I/51eAqEfUr4L._AC_UL320_.jpg](https://m.media-amazon.com/images/I/51eAqEfUr4L._AC_UL320_.jpg)

**Comment by 1achy** [comment]
https://github.com/rzeldent/esp32-smartdisplay


Library

**Comment by strange-v** [comment]
Hi.

As I'm currently focusing on developing the new version of HA Deck that comes with additional widgets, styles, and other features, I won't be able to provide support for new boards. Once the initial release is ready, I need to figure out the best way to do it, as there are numerous screens to consider, and it won't be feasible for me to test and maintain them all.

For now, creating a new hardware component in a separate repository is the recommended way for easy integration with HA Deck.

**Comment by 1achy** [comment]
tks for your answer... https://github.com/1achy/ha_deck_-ILI9341_2.8

**Comment by 1achy** [comment]
this board is very interesting becouse is very cheap other my development : https://github.com/1achy/ESPHOME-esp32-2432s028r-LCD

**Comment by ToViNi** [comment]
Maybe you can take a look at what I have done.  I don't have the same board as you, but one size bigger.   [](https://github.com/ToViNi/ha_deck)
