### ISSUE TITLE
how to rotate display?

### ISSUE THREAD

**Issue by lukedoomer** [strange-v/ha_deck#7]
which file and where should I put rotation configuration in?

**Comment by strange-v** [comment]
It can be done in a few ways, but the easiest should be changing this line https://github.com/strange-v/ha_deck/blob/abe4194daccb51334c9f920e0177760c9e79b3ed/components/hd_device_sc01_plus/hd_device_sc01_plus.cpp#L56

The [hardware rotation](https://github.com/strange-v/ha_deck/blob/abe4194daccb51334c9f920e0177760c9e79b3ed/components/hd_device_sc01_plus/LGFX.cpp#L40) will be faster, but it also requires rotation of touch points and AFAIR, it isn't handled by the LovyanGFX automatically.
