### ISSUE TITLE
How to change background (bg_480x320)

### ISSUE THREAD

**Issue by genasoft** [strange-v/ha_deck#9]
Changing the background (online image converter, with colour format of CF-TRUE-COLOR and naming the file bg_480x320 - https://lvgl.io/tools/imageconverter) produces the following error upon compile:
/src/esphome/components/hd_device_sc01_plus/hd_device_sc01_plus.cpp.o:(.literal._ZN7esphome9hd_device12HaDeckDevice5setupEv+0x2c): undefined reference to `bg_480x320'
If the modified file is replaced with the original file, the error persists. Only deleting the fork and forking the project again works.
You can see the fork at: https://github.com/genasoft/ha_deck/tree/main

**Comment by strange-v** [comment]
I've no problems building and using your fork

![example](https://github.com/strange-v/ha_deck/assets/3875529/6df5bd59-8ddf-415c-9c9f-a1e535ca825a)

Have you tried `Clean Build Files` option?

**Comment by genasoft** [comment]
Yes, I have. Clean build and it fails at the same place.
What is weirder is that if I build from your repo, all goes well. If I fork your repo, the build is OK. But, if I replace the background file, even with the original (the one from your repo), it fails.

**Comment by genasoft** [comment]
I got it going. I had to go into the docker container and clean up the previous builds. For some reason, from the GUI, the clean is not done complete.

**Comment by strange-v** [comment]
Ahh, I had similar cases during the development, but only after massive changes.

> On another note, are there any plans on rotation of the display (from horizontal to vertical)?

Yes. I plan to add a software rotation to the configuration in the next version. For now, you can try suggestions from [here](https://github.com/strange-v/ha_deck/issues/7).
